name: user-entity build pipeline

env:
  AZURE_FUNCTIONAPP_NAME: 'user-entity'

on:
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'
        required: true
        default: 'warning'
        type: choice
        options:
        - info
        - warning
        - debug
  pull_request:
    branches:
      - main
    paths:
      - traqueno-backend/user-entity/**
  push:
    branches:
      - main
    paths:
      - traqueno-backend/user-entity/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt-hotspot'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Cache Gradle packages
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Change gradlew permissions
        run: chmod +x ./gradlew
        working-directory: traqueno-backend/user-entity/

      - name: Build with Gradle
        run: ./gradlew build -Dquarkus.package.type=uber-jar
        working-directory: traqueno-backend/user-entity/

      - uses: actions/upload-artifact@master
        with:
          name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          path: ${{ env.AZURE_FUNCTIONAPP_NAME }}/${{ env.AZURE_FUNCTIONAPP_NAME }}-entrypoint/${{ env.AZURE_FUNCTIONAPP_NAME }}-entrypoint-rest/build/${{ env.AZURE_FUNCTIONAPP_NAME }}-entrypoint-rest-1.0-SNAPSHOT-runner.jar

  deploy:
    if: github.event_name != 'pull_request' && github.event_name == 'workflow_dispatch'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          path: ${{ env.AZURE_FUNCTIONAPP_NAME }}-entrypoint-rest-1.0-SNAPSHOT-runner.jar

      - name: Copy jar file into azure-deploy folder
        run: cp ${{ env.AZURE_FUNCTIONAPP_NAME }}-entrypoint-rest-1.0-SNAPSHOT-runner.jar/${{ env.AZURE_FUNCTIONAPP_NAME }}-entrypoint-rest-1.0-SNAPSHOT-runner.jar ${{ env.AZURE_FUNCTIONAPP_NAME }}/azure-deploy/

      - name: Zip azure-deploy folder
        run: |
          cd ${{ env.AZURE_FUNCTIONAPP_NAME }}/azure-deploy/
          zip -r function_app.zip .

      - name: 'Run Azure Functions action'
        uses: Azure/functions-action@v1
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
          package: '${{ env.AZURE_FUNCTIONAPP_NAME }}/azure-deploy/function_app.zip'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE_USER_ENTITY }}
